export const mapUserToModel = ({
  id,
  username,
  name,
  bio,
  email,
  password,
  type,
  verify,
  gender,
  profile_image,
  phone_number,
  is_private,
  is_new_user,
  created_at,
  updated_at,
}) => ({
  id,
  username,
  name,
  bio,
  email,
  password,
  type,
  verify,
  gender,
  profileImage: profile_image,
  phoneNumber: phone_number,
  isPrivate: is_private,
  isNewUser: is_new_user,
  createdAt: created_at,
  updatedAt: updated_at,
});

export const columnMapUpdate: { [key: string]: string } = {
  profileImage: 'profile_image',
  phoneNumber: 'phone_number',
};
